name: Java_Installation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: sudo apt install default-jre
      - run: sudo apt update && sudo apt install default-jdk
      - run: echo "Java installation complete!"

      - run: |  # Optional comment for future steps
          echo "Add additional steps to build, test, and deploy your project."
